"""Bundled sample datasets, offered as one-click loaders on the empty state.

WHY this is a server endpoint rather than three files shipped in the frontend's
public/ directory: the samples are generated by scripts/make_samples.py and are
gitignored, so they exist on disk next to the backend and nowhere else.
Duplicating them into the frontend build would mean two copies that can drift,
and the point of the samples is that they are exactly what the test suites run
against.

The empty state is where a first-time user decides whether this tool is worth
their own data. Making them find a CSV before they can see anything is the
single easiest way to lose them, so loading a real dataset is one click.
"""

from __future__ import annotations

import logging
import os
from typing import Dict, List

from fastapi import APIRouter, HTTPException, status

from backend.models import SampleInfo, UploadResponse
from backend.routers.upload import ingest

logger = logging.getLogger(__name__)

router = APIRouter(tags=["samples"])

SAMPLES_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "samples",
)

# A fixed registry, keyed by a slug. The key is what the client sends, and it is
# looked up in this dict rather than joined onto a path -- so a request for
# "../../.env" is a 404 by construction, not by a sanitiser somebody has to
# remember to write correctly.
SAMPLES: Dict[str, Dict[str, str]] = {
    "timeseries": {
        "filename": "sales_timeseries.csv",
        "label": "Daily sales",
        "description": "400 days of revenue with a trend, weekly seasonality, mixed "
                       "date formats and a few unparseable rows.",
    },
    "geo": {
        "filename": "air_quality_geo.csv",
        "label": "Air quality sensors",
        "description": "Timestamped PM2.5 readings from stations scattered across "
                       "the UK, with coordinates.",
    },
    "tabular": {
        "filename": "employees_tabular.csv",
        "label": "Employee records",
        "description": "Cross-sectional staff data: salary, experience and "
                       "satisfaction by department.",
    },
}


def _path_for(key: str) -> str:
    return os.path.join(SAMPLES_DIR, SAMPLES[key]["filename"])


@router.get("/samples", response_model=List[SampleInfo])
def list_samples() -> List[SampleInfo]:
    """List the sample files that are actually present on disk.

    Missing files are omitted rather than reported as errors: samples/ is
    gitignored and regenerated by a script, so a fresh clone that has not run it
    yet should show an empty-but-working state, not three broken buttons.
    """
    available: List[SampleInfo] = []
    for key, meta in SAMPLES.items():
        path = _path_for(key)
        if os.path.isfile(path):
            available.append(
                SampleInfo(
                    key=key,
                    filename=meta["filename"],
                    label=meta["label"],
                    description=meta["description"],
                    n_bytes=os.path.getsize(path),
                )
            )
    return available


@router.post(
    "/samples/{key}",
    response_model=UploadResponse,
    status_code=status.HTTP_201_CREATED,
)
def load_sample(key: str) -> UploadResponse:
    """Load a bundled sample through the exact same path as a real upload."""
    if key not in SAMPLES:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND, detail=f"No sample named {key!r}."
        )

    path = _path_for(key)
    try:
        with open(path, "rb") as handle:
            content = handle.read()
    except OSError as exc:
        logger.warning("Sample %s unreadable at %s: %s", key, path, exc)
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=(
                f"The {key!r} sample is not on disk. Run "
                f"`python scripts/make_samples.py` to generate it."
            ),
        ) from exc

    session, frame = ingest(content, SAMPLES[key]["filename"])
    return UploadResponse(
        session_id=session.id,
        filename=session.filename,
        n_rows=int(len(frame)),
        n_cols=int(frame.shape[1]),
        profile=session.profile,
    )
